### ISSUE TITLE
Authoritative Source?

### ISSUE THREAD

**Issue by davidlday** [cmusphinx/cmudict#12]
I'm assuming this repo is the best source for obtaining the cmudict files, but can you confirm? Or is the source found at [The CMU Pronouncing Dictionary](http://www.speech.cs.cmu.edu/cgi-bin/cmudict) site kept up-to-date?

And, if this repo is the best source, are there any plans to start tagging releases here?

Thanks!

**Comment by nshmyrev** [comment]
> I'm assuming this repo is the best source for obtaining the cmudict files, but can you confirm? 

Absolutely

> Or is the source found at The CMU Pronouncing Dictionary site kept up-to-date?

No idea

> And, if this repo is the best source, are there any plans to start tagging releases here?

There are no significant updates and no plans to have releases yet.

**Comment by davidlday** [comment]
Thank you!
