### ISSUE TITLE
Russian Dictionary?

### ISSUE THREAD

**Issue by zhanwenchen** [cmusphinx/cmudict#15]
Hi. Your website [article](https://cmusphinx.github.io/wiki/tutorialdict/) mentions a Russian dict, but I could not find it. Would you please point me to the right direction?

**Comment by Coeur** [comment]
https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Russian/

**Comment by nshmyrev** [comment]
Exactly, thanks,, Antoine!

The first one is recommended.
