### ISSUE TITLE
My corrections

### ISSUE THREAD

**Issue by benkasminbullock** [cmusphinx/cmudict#17]
For your reference: in my file of errata for cmudict, I have SUTTER, BENTEN, HARRIS, HARRIS' HARRIS'S, and NABIL marked as erroneous. The final vowel of SUTTER seems to be wrong, the second vowel of BENTEN is marked as IH0 but a word with that pronunciation (written benten and pronounced ben-teen) doesn't seem to exist, and all of the HARRIS entries have EH1 as the first vowel, as if "hay-ris". NABIL is missing the final L sound, but this name seems to have an L sound:

https://translate.google.com/#ar/en/%D9%86%D8%A8%D9%8A%D9%84%E2%80%8E

**Comment by benkasminbullock** [comment]
One more correction, "borrowers'" with an apostrophe should be the same as without, but currently you have
```
borrowers' B AO1 R AH0 ER0 Z
borrowers B AA1 R OW0 ER0 Z
```
The top one is definitely wrong.

**Comment by nshmyrev** [comment]
Thank you!

**Comment by benkasminbullock** [comment]
I don't understand why this is closed, since most of the issues I addressed in the top have not been resolved, only the second post's issue was addressed.
