### ISSUE TITLE
Current state of updates, contribution procedure?

### ISSUE THREAD

**Issue by danmartinez** [cmusphinx/cmudict#29]
As of July 2022, is this repository still being actively (or at least somewhat regularly) maintained? If so, what is the preferred avenue for contributing corrections/additions? Should we follow the usual git workflow of fork->push->pull request? Or should changes be emailed directly to someone as in the past? Thank you.

**Comment by dhgutteridge** [comment]
I see from looking at the project activity that pull requests are being accepted.  It would definitely be nice if that was confirmed in the README as the preferred method now, if that's indeed the case.

**Comment by Alexir** [comment]
Right. Kevin Lenzo seems to be handling pulls at this point; I've been a bit lazy...

**Comment by danmartinez** [comment]
> Right. Kevin Lenzo seems to be handling pulls at this point; I've been a bit lazy...

Great, thanks for the response!
