### ISSUE TITLE
How to convert cmudict-0.7b or cmudict-0.7b.dict in to FST format to use it with phonetisaurus?

### ISSUE THREAD

**Issue by G10DRAS** [cmusphinx/cmudict#3]
I am looking for a simple procedure to generate FST (finite state transducer) from cmudict-0.7b or cmudict-0.7b.dict, which will be used with phonetisaurus.

I tried following set of commands (phonetisaurus Aligner, Google NGramLibrary and phonetisaurus arpa2wfst) and able to generate FST but it didn't work. I am not sure where I did a mistake or miss any step. I guess very first command ie phonetisaurus-align, is not correct.

phonetisaurus-align --input=cmudict.dict --ofile=cmudict/cmudict.corpus --seq1_del=false
ngramsymbols < cmudict/cmudict.corpus > cmudict/cmudict.syms
/usr/local/bin/farcompilestrings --symbols=cmudict/cmudict.syms --keep_symbols=1 cmudict/cmudict.corpus > cmudict/cmudict.far
ngramcount --order=8 cmudict/cmudict.far > cmudict/cmudict.cnts
ngrammake --v=2 --bins=3 --method=kneser_ney cmudict/cmudict.cnts > cmudict/cmudict.mod
ngramprint --ARPA cmudict/cmudict.mod > cmudict/cmudict.arpa
phonetisaurus-arpa2wfst-omega --lm=cmudict/cmudict.arpa > cmudict/cmudict.fst

I tried fst with phonetisaurus-g2p as follows:

phonetisaurus-g2p --model=cmudict/cmudict.fst --nbest=3 --input=HELLO --words

But it didn't return anything.... Appreciate any help one this matter.

**Comment by nshmyrev** [comment]
it is case-sensitive, so you probably want --input=hello

You can also download precompiled FSTs for phonetisaurus on our website in downloads.

**Comment by G10DRAS** [comment]
I used cmudict-tool (https://github.com/rhdunn/cmudict-tools)

cmudict-tools --format=sphinx --remove-context-entries  --remove-stress print cmudict.dict > cmudict.lex
phonetisaurus-align --input=cmudict.lex --ofile=cmudict/cmudict.corpus --seq1_del=false
...........

Now FST works as expected

phonetisaurus-g2p --model=cmudictfst/cmudict7b.fst   --nbest=3 --input=HELLO --words

HELLO   23.4177 HH EH L OW
HELLO   23.4205 EH L OW
HELLO   27.289  EY CH EH L OW

**Comment by to-schi** [comment]
> it is case-sensitive, so you probably want --input=hello
> 
> You can also download precompiled FSTs for phonetisaurus on our website in downloads.

Can you specify the website for precompiled FST download?
