### ISSUE TITLE
3 periods are not an ellipsis

### ISSUE THREAD

**Issue by Daniel-Hug** [cmusphinx/cmudict#4]
Here is [line 33 of cmudict.vp](https://github.com/cmusphinx/cmudict/blob/master/cmudict.vp#L33):

```
...ellipsis IH0 L IH1 P S IH0 S
```

All other lines begin with a single punctuation character. Having 3 periods here presents a parsing problem.

**Comment by nshmyrev** [comment]
This is a special part for WSJ VP task training, cmudict.vp should not be used in course of work. Our default dictionaries do not include it.
